### ISSUE TITLE
Feature Request: Nested subfolders support

### ISSUE THREAD

**Issue by simonmcnair** [Yinzo/sd-webui-Lora-queue-helper#6]
Great script but doesn't show nested subfolders.  eg fictional/dccomics/batman.

Thanks for your efforts though and I can understand why nesting would be a pain programatically.

**Comment by Yinzo** [comment]
I think I can support that, maybe these days. Maybe not very elegant, but at least I can make it work on nested path.

**Comment by Yinzo** [comment]
Done, if there is any problem, feel free to tell me in this issue.

**Comment by simonmcnair** [comment]
thanks.  Weird question you may have insight into.  Somehow a LORA in a different folder got triggered, it has the same activation word, but the filename is different.  Any ideas if/how that could happen ?

**Comment by Yinzo** [comment]
> thanks. Weird question you may have insight into. Somehow a LORA in a different folder got triggered, it has the same activation word, but the filename is different. Any ideas if/how that could happen ?

Is this a problem when using this script, or it appears all the time no matter with/without script ? 

In A1111's default settings, LoRA is used when its alias (also name "output_name" in meta data of LoRA, it's a author configured trigger word from model file) is included in the prompt, no matter LoRA's path, so if there are multiple LoRA with same alias, it will cause A1111 don't know which LoRA should be used.

You can change that in the A1111's settings > Extra Networks > "When adding to prompt, refer to Lora by", and choose "Filename" instead of "Alias from file", that should make A1111 choose LoRA by filename but not it's alias.

Also you can change the alias name manually, using this tool [https://lorainfo.tools/](https://lorainfo.tools/), change the "ss_output_name" in Meta data part to anything you want, but keep it unique in your lora collections.

**Comment by simonmcnair** [comment]
Thanks for the input.  Changing the A1111 setting fixed this.  All looks good, cheers.
